### ISSUE TITLE
Weird anomaly with a certain word

### ISSUE THREAD

**Issue by AndiGr95** [msiemens/HypheNN-de#5]
Hi, first of all thank you for sharing this on Github @msiemens :)

I am having issues with the hyphenation of the word "Geo" or geo-like words in general. 
In my dataset I prepared all words starting with "Geo, Leo...." etc like this "Ge·o..., Le·o...".

After training the output specifically for "Geo" looks like this

Input: Geo
Hyphenation: Ge·oo

same for Leo, Feo, Meo etc
Input: Leo
Hyphenation: Le·oo
....
....

It adds for some reason an additional o at the end. The hyphenation is correct though. Does anyone have this issue or would you have any idea why it does this? Help would be appreciated!

It works totally fine with other words

example:

Input: Donaudampfschifffahrtsgesellschaftskapitänswitwe
Hyphenation: Do·nau·dampf·schiff·fahrts·ge·sell·schafts·ka·pi·täns·wit·we

Input: Silbentrennung
Hyphenation: Sil·ben·tren·nung

ps: I am new to DL and NNs

Greetings
Andi

**Comment by msiemens** [comment]
Thanks for reporting this, @AndiGr95! Turns out I never tested with short words (three characters or less 🤷‍♂️ Now, words with one or two characters are skipped while words with three characters are now handled correctly. I guess there might be languages other than German where words with one or two characters could be hyphenated, but that would require more reworking of the window logic…
